### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by drusch91** [Auhrus/theisle-evrima-docker-server#4]
**Describe the error as best you can**
![image](https://github.com/user-attachments/assets/8451b151-2429-43e7-be0d-39521155af4c)

**How to reproduce it (if it is)**
1. 

**What should actually happen**

**Have you tried re-downloading/re-setting up the image yet?**

**Specs**
- Operating System:  Ubuntu LTS
- Version:  24.04.01
- Docker Version: 27.3.1

**Screenshots**
![image](https://github.com/user-attachments/assets/9dc03d3d-7849-4fc8-a72d-361e5cfef71a)

**Additional Stuff**
Add more information about the problem here.

**Comment by Auhrus** [comment]
Hello, I cannot reproduce your error messages myself.
What you can check:
1. check that the permissions in the volume folder are set correctly. All files and folders must have the owner and group 1000.
You can set this with this command in the volume folder
`chown 1000:1000 YOUR_VOLUME_FOLDER/ -R`

2. check if you have the new [Game.ini](https://github.com/Auhrus/theisle-evrima-docker-server/blob/1b9112b8de320260a16b0388b7af81ad9db28c2b/basic-configs/Game.ini).
There have been some changes to the [Game.ini](https://github.com/Auhrus/theisle-evrima-docker-server/blob/1b9112b8de320260a16b0388b7af81ad9db28c2b/basic-configs/Game.ini) since the last patch.
I would recommend you to download the Game.ini again from my repo and set it up again with your settings.

Another question is, can you find and join the server in the game or do you get an error message?

**Comment by drusch91** [comment]
Hi, here are the server logs, I checked all the files have an owner of 1000:1000.
[TheIsle.log](https://github.com/user-attachments/files/17269629/TheIsle.log)

I used your Game.ini config and did not change it in any way.

**Comment by Auhrus** [comment]
Have you tried it on another server? Does the same thing happen there?
Have you tried to delete everything (except the config and the player saves) and download it again?
Also, this error message looks to me like the server is hanging up somewhere.
[Line 637 `Hang detected on GameThread (thread hasn't sent a heartbeat for 180.00 seconds)`]

**Comment by drusch91** [comment]
Yes, I completely deleted all the files.
Unfortunately, I don't have another server

**Comment by drusch91** [comment]
I solved the problem after the console wrote "CORE DUMP". The server started and everything worked as expected, but I still didn't understand what the error message was about.
